### ISSUE TITLE
Command is not blocking in the latest embassy repo

### ISSUE THREAD

**Issue by ninjasource** [HaoboGu/eg-demo#1]
Hi,

While attempting to compile your repo I encountered the following error:

```rust
error[E0599]: no method named `unwrap` found for opaque type `impl Future<Output = Result<(), embassy_stm32::ospi::OspiError>>` in the current scope
   --> src/w25q.rs:198:41
    |
198 |         self.ospi.command(&transaction).unwrap();
```

This happens on both your branch and the main embassy repo. How did you originally send blocking ospi calls?

**Comment by HaoboGu** [comment]
yeah the implementation has some bugs, adding .await before unwrap() solves this

**Comment by HaoboGu** [comment]
I just didn't push the updated code.
